version: 3.8
services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - net
networks:
  net:
